# Generated by Django 3.0.7 on 2020-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_appartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
    ]
