# Generated by Django 3.0.7 on 2020-07-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='appartment',
        ),
    ]
