# Generated by Django 2.2.5 on 2019-09-23 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Code', models.CharField(max_length=20)),
                ('Cart_Price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Cart_Quantity', models.IntegerField()),
                ('Cart_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Delivery_Charge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=240)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d/')),
                ('image_1', models.ImageField(upload_to='product/%Y/%m/%d/')),
                ('image_2', models.ImageField(upload_to='product/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=250)),
                ('Product_Code', models.CharField(max_length=20, unique=True)),
                ('Product_slug', models.SlugField()),
                ('Product_Description', models.TextField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StockOut', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('discount', models.IntegerField()),
                ('Trending', models.BooleanField(default=False)),
                ('Product_Update', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product_Images')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=240)),
                ('Street_Address', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=20)),
                ('ZIP_Code', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Payment_Method', models.CharField(max_length=240)),
                ('Delivery_Charge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
