# Generated by Django 2.2.5 on 2019-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190923_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='product/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Product_Images',
        ),
    ]
