# Generated by Django 2.2.8 on 2020-01-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190923_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Product_Code',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
