# Generated by Django 3.0.7 on 2020-06-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_auto_20200125_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceId', models.CharField(default='', max_length=250)),
                ('Pending', models.BooleanField(default=True)),
                ('Confirmed', models.BooleanField(default=False)),
                ('Proceesing', models.BooleanField(default=False)),
                ('Packed', models.BooleanField(default=False)),
                ('Shipped', models.BooleanField(default=False)),
                ('Delivered', models.BooleanField(default=False)),
                ('ProductCode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
