# Generated by Django 3.0.7 on 2020-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_odertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odertracking',
            name='InvoiceId',
            field=models.CharField(max_length=250),
        ),
    ]
