# Generated by Django 3.0.7 on 2020-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200626_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='odertracking',
            name='Date',
            field=models.CharField(default='', max_length=250),
        ),
    ]
