# Generated by Django 3.0.7 on 2020-06-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_odertracking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('state_country', models.CharField(max_length=255)),
                ('street_Address', models.CharField(max_length=255)),
                ('appertment', models.CharField(max_length=255, null=True)),
                ('town', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('payment_Method', models.CharField(max_length=255)),
            ],
        ),
    ]
