# Generated by Django 3.0.8 on 2020-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
