# Generated by Django 3.0.8 on 2020-07-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_transactions_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
