# Generated by Django 3.0.8 on 2020-07-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_transactions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
    ]
