# Generated by Django 3.0.8 on 2020-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200704_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Total',
            field=models.CharField(max_length=255),
        ),
    ]
